apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysql-kv-secrets
spec:
  provider: azure
  secretObjects:
    - secretName: mysql-secrets
      type: Opaque
      data:
        - objectName: mysql-root-password
          key: MYSQL_ROOT_PASSWORD      
        - objectName: mysql-database
          key: MYSQL_DATABASE           
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: kv-3tier-mysql
    tenantId: aac42910-b03a-44c1-b372-7cee5c67a2d5
    objects: |
      array:
        - |
          objectName: mysql-root-password
          objectType: secret
        - |
          objectName: mysql-database
          objectType: secret

