# -----------------------------
# MySQL Configuration
# -----------------------------
mysql:
  image: mysql
  tag: "8.0"
  database: bookDatabase
  service:
    type: ClusterIP
    port: 3306

# -----------------------------
# Backend (Spring Boot)
# -----------------------------
backend:
  image: aayush595/mybook-backend
  tag: "1.0"
  replicaCount: 1
  service:
    type: ClusterIP
    port: 8080

# -----------------------------
# Frontend (Angular)
# -----------------------------
frontend:
  image: aayush595/mybook-frontend
  tag: "FINAL"
  replicaCount: 1
  service:
    type: LoadBalancer
    port: 80
